### ISSUE TITLE
how to change weather unit ?

### ISSUE THREAD

**Issue by zhangjie2012** [bcbcarl/emacs-wttrin#13]
default show `°F`，but I want show `℃`, is there one way ?

**Comment by feklee** [comment]
To change [units][1] to metric, add the `m` option to the location: (entering a question mark in the minibuffer is a challenge, but can be overcome with copy and paste)

    Berlin?m

To get a list of options, use as location:

    /:help

By the way, not mentioned there is the `I` option, which makes colors readable on white background. It would be nice if these options could be stored in a customizable variable for all locations.

[1]: https://github.com/chubin/wttr.in/blob/0717d05cbb74d48bfa908a439cee9dfe08096116/README.md#weather-units
