### ISSUE TITLE
Tag a release :)

### ISSUE THREAD

**Issue by AdrieanKhisbe** [bcbcarl/emacs-wttrin#5]
Hey @bcbcarl :smiley: 
Nice [and sunny] plugin!

Could you git tag some release, so your package could be built on melpa.stable? :)

http://stable.melpa.org/#/wttrin

**Comment by bcbcarl** [comment]
No problem. Thank you.

**Comment by AdrieanKhisbe** [comment]
No hurry :smiley: 
When you have the opportunity to :wink:

**Comment by bcbcarl** [comment]
https://github.com/bcbcarl/emacs-wttrin/releases/tag/v0.1.0

**Comment by AdrieanKhisbe** [comment]
Perfect! :)
