### ISSUE TITLE
Misalignment

### ISSUE THREAD

**Issue by huylenq** [bcbcarl/emacs-wttrin#7]
Misalignment of the border characters. I'm using this on spacemacs.

<img width="1050" alt="screen shot 2017-02-03 at 8 41 52 am" src="https://cloud.githubusercontent.com/assets/508279/22576321/58efcd84-e9ed-11e6-8750-e83d6c3efd9e.png">

**Comment by bcbcarl** [comment]
Misalignment issue is not related to this package.

You can check the following references:

* https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bintl/chinese#set-monospaced-font-size设置等宽字体
* https://github.com/hick/emacs-chinese
